proversity-org/rocket-chat-extension

requirements.txt, rocketc/rocketc.py, rocketc/tests/test_rocketChat.py, tox.ini
Add the test for the initial xblock methods
=> Add unittest for the existing methods and/add tests

rocketc/openedx_dependencies.py, rocketc/requirements/test.txt, rocketc/rocketc.py, rocketc/tests/test_rocketChat.py, tox.ini
This branch allows to add the profile image from edx-platform to rocketChat.
=> Set profile image  and/add profile image

rocketc/rocketc.py, rocketc/tests/test_rocketChat.py
This pull request allows to get the rocketchat api service url from the platform settings or use a default value.
=> Add a new method to set the rocketchat api url

rocketc/static/css/rocketc.css, rocketc/static/html/rocketc.html
This branch allows to fill all available horizontal space with the rocketChat window
=> Add responsive behavior

rocketc/rocketc.py, rocketc/static/html/rocketc.html, setup.cfg, setup.py
This branch allows to get the user an password from the ed-platform settings
=> Read user setting and fixing errors

rocketc/rocketc.py, rocketc/static/html/studio.html
Allows to see the default name in studio edit
=> Add a hint for the view in studio to create channels

rocketc/rocketc.py
Add the display name to show in studio
=> Add the name to show in Studio

custom_css.css
The necessary CSS to remove the logout button.
=> Add a new css file that hide the logout button

login_script.js
Modify the script that allows automatic login
=> Remove function onload

rocketc/rocketc.py
Create a new method to disable public channels
=> Create method to disable public channels

rocketc/rocketc.py
=> Add logging

rocketc/rocketc.py, rocketc/tests/test_rocketChat.py
=> Fixing tests

rocketc/rocketc.py, rocketc/static/html/rocketc.html, setup.cfg, setup.py
That fixes the selection of main view
=> Fixing error when the main view is selected

rocketc/static/html/rocketc.html, rocketc/static/js/src/rocketc.js, setup.cfg, setup.py
Add a new message to show in outline section
=> Add a new message to show in outline section

rocketc/api_rocket_chat.py, rocketc/api_teams.py, rocketc/rocketc.py, rocketc/static/css/rocketc.css, rocketc/static/html/rocketc.html, rocketc/static/js/src/rocketc.js, rocketc/tests/test_rocketChat.py, setup.cfg, setup.py
Add two buttons in team view to leave and create a user. Anyone can do this
=> Implementing buttons to create and leave a channel in team view

rocketc/rocketc.py
This  remove special character in groups searching
=> filter special characters in method get list of groups

rocketc/static/css/rocketc.css
@diegomillan 
@nicovanniekerk 
@jfavellar90 
change color for panels in rocket chat
=> change colors of panel in rocket chat

rocketc/rocketc.py, rocketc/static/js/src/rocketc.js, setup.cfg, setup.py
Filter special character  and remove unnecessary css and js on studio
=> Fixing studio and filter special characters

rocketc/rocketc.py
=> Adding support to mobiles

rocketc/static/html/rocketc.html, rocketc/static/js/src/rocketc.js, setup.cfg, setup.py
Add options to select in input leave
=> Add a teams list to leave

rocketc/static/html/rocketc.html, setup.cfg, setup.py
=> Fix quotes

rocketc/rocketc.py, rocketc/static/html/rocketc.html, rocketc/static/js/src/rocketc.js, setup.cfg, setup.py
=> Fix js errors

rocketc/api_rocket_chat.py, rocketc/openedx_dependencies.py, rocketc/rocketc.py, rocketc/static/js/src/studio_view.js, rocketc/tests/test_rocketChat.py, setup.cfg, setup.py
This allows to grade contributions to Rocket.Chat, reward students who are engaged with the discussion.
https://docs.google.com/document/d/1Cd-wuyezWRbaDKFfi_5v2RN59hCUqMYZ9r8HkTCHsiM/edit
=> Grading Discussions

rocketc/openedx_dependencies.py, rocketc/rocketc.py, rocketc/tests/test_rocketChat.py
=> Fixing test

rocketc/rocketc.py
Fixing error with the select in studio
=> Fixing error for specific channel

rocketc/static/js/src/studio_view.js
Add dash and get group name from data
=> Add dash to responseCreate 

rocketc/static/html/rocketc.html
=> fix errors

rocketc/static/css/rocketc.css
@nicovanniekerk 
@die gomillan 
@ericfab179 
change color black of chat to white
this is part of PE-108
=> PE-108 change color of panels

setup.cfg, setup.py
=> Bump version: 0.2.21 → 0.2.22

rocketc/api_rocket_chat.py, rocketc/rocketc.py, rocketc/static/html/rocketc.html, rocketc/static/js/src/rocketc.js, setup.cfg, setup.py
Using cache to keep the rocketchat user data and implementing a new logout method
=> Logout method

rocketc/static/js/src/rocketc.js, setup.cfg, setup.py
These changes hide the iframe until it is loaded, in order to prevent the frame steals the focus. This is a quick fix for  this https://github.com/RocketChat/Rocket.Chat/issues/9347
=> PE-149 Prevent iframe steals focus

rocketc/static/js/src/rocketc.js
Adding a condition to avoid to set "beacon_rc" as null.
=> Add a condition to avoid set "beacon_rc" equals to null

setup.cfg, setup.py
=> Bump version: 0.2.25 → 0.2.26

setup.cfg, setup.py
=> Bump version: 0.3.0 → 0.4.0

rocketc/rocketc.py, rocketc/static/html/rocketc.html
1 Use cache to store the response
2 Get the team object from the model instead of use the API
=> PE-541 Improve performance
